/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_asus_myndktest2_PatchUtils */

#ifndef _Included_com_example_asus_myndktest2_PatchUtils
#define _Included_com_example_asus_myndktest2_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_asus_myndktest2_PatchUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_example_asus_myndktest2_PatchUtils_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
