/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_asus_myndktest2_NDKUtils */

#ifndef _Included_com_example_asus_myndktest2_NDKUtils
#define _Included_com_example_asus_myndktest2_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_asus_myndktest2_NDKUtils
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_asus_myndktest2_NDKUtils_stringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
